<template>
  <main class="min-h-screen bg-stone-100 p-4 dark:bg-stone-950 sm:p-8"><section class="mx-auto max-w-2xl rounded-3xl border bg-background p-6 shadow-xl sm:p-10"><p class="text-xs font-bold tracking-[0.2em] text-amber-700">ATELIÊ · ORÇAMENTO SEGURO</p><div v-if="loading" class="py-20 text-center text-muted-foreground">Carregando orçamento…</div><div v-else-if="budget"><h1 class="mt-3 text-3xl font-bold">{{ budget.ordem.codigoRastreio }}</h1><p class="mt-1 text-muted-foreground">Olá, {{ budget.ordem.cliente }}. Revise a proposta para suas peças.</p><div class="mt-6 space-y-3 rounded-2xl bg-muted/60 p-5"><p v-for="piece in budget.ordem.pecas" :key="piece.codigoRastreio"><strong>{{ piece.codigoRastreio }}</strong> — {{ piece.descricao }}</p></div><div class="mt-6 rounded-2xl border p-5"><p class="text-sm text-muted-foreground">Orçamento versão {{ budget.orcamento.versao }}</p><div v-for="service in budget.orcamento.servicos" :key="service.descricao" class="mt-3 flex justify-between"><span>{{ service.quantidade }}× {{ service.descricao }}</span><span>R$ {{ Number(service.valor).toFixed(2) }}</span></div><div class="mt-5 flex justify-between border-t pt-4 text-xl font-bold"><span>Total</span><span>R$ {{ Number(budget.orcamento.valorFinal).toFixed(2) }}</span></div></div><p class="mt-4 text-sm text-muted-foreground">Este link expira em {{ new Date(budget.orcamento.expiraEm).toLocaleString('pt-BR') }}.</p><textarea v-model="observation" class="mt-6 min-h-24 w-full rounded-xl border bg-background p-3" placeholder="Observação para o ateliê (opcional)" /><div v-if="!finished" class="mt-4 grid gap-3 sm:grid-cols-2"><Button variant="outline" :disabled="sending" @click="decide('RECUSAR')">Recusar orçamento</Button><Button :disabled="sending" @click="decide('APROVAR')">Aprovar orçamento</Button></div><p v-else class="mt-5 rounded-xl bg-emerald-500/10 p-4 text-emerald-700 dark:text-emerald-300">Sua decisão foi registrada. Obrigado.</p></div><div v-else class="py-20 text-center"><h1 class="text-2xl font-bold">Orçamento indisponível</h1><p class="mt-2 text-muted-foreground">O link expirou, foi substituído ou não é válido.</p></div></section></main>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { useToast } from 'vue-toastification'
import http from '@/utils/axios'
import { Button } from '@/components/ui/button'
const route = useRoute(); const toast = useToast(); const loading = ref(true); const budget = ref<any>(); const observation = ref(''); const sending = ref(false); const finished = ref(false)
async function load() { try { const { data } = await http.get(`/v1/ourive/publico/orcamentos/${route.params.token}`); budget.value = data.data } catch { budget.value = null } finally { loading.value = false } }
async function decide(decisao: 'APROVAR' | 'RECUSAR') { sending.value = true; try { await http.post(`/v1/ourive/publico/orcamentos/${route.params.token}/decisao`, { decisao, observacao: observation.value || undefined }); finished.value = true } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível registrar a decisão.') } finally { sending.value = false } }
onMounted(load)
</script>
