<template>
  <section v-if="order" class="space-y-6">
    <div class="flex flex-col justify-between gap-4 rounded-2xl border border-amber-500/20 bg-gradient-to-r from-amber-500/10 to-transparent p-6 lg:flex-row lg:items-center"><div><Button variant="ghost" size="sm" class="mb-2 -ml-2" @click="router.push({ name: 'ourive-ordens' })"><ArrowLeft class="mr-2 h-4 w-4" />Ordens</Button><p class="text-xs font-semibold tracking-[0.18em] text-amber-700 dark:text-amber-300">CUSTÓDIA · {{ order.codigoRastreio }}</p><h1 class="mt-1 text-3xl font-bold">{{ order.ordemServico?.descricao }}</h1><p class="mt-1 text-sm text-muted-foreground">{{ order.ordemServico?.Cliente?.nome }} · {{ order.ordemServico?.Cliente?.telefone || 'Sem telefone' }}</p></div><div class="flex flex-wrap gap-2"><Badge variant="secondary">{{ label(order.status) }}</Badge><Button v-if="can('PRODUCAO') && order.status === 'ORCAMENTO'" @click="start">Iniciar produção</Button><Button v-if="can('ENTREGAR') && order.status === 'REVISAO'" @click="deliver">Entregar e faturar</Button><Button v-if="can('ORCAMENTO') && !closed" variant="destructive" @click="cancel">Cancelar</Button></div></div>

    <div class="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
      <div class="space-y-6"><Card><CardHeader><CardTitle>Peças sob custódia</CardTitle><CardDescription>Fotos, checklist de recebimento e rastreio individual.</CardDescription></CardHeader><CardContent class="space-y-5"><div v-for="piece in order.pecas" :key="piece.id" class="rounded-xl border p-4"><div class="flex flex-col justify-between gap-2 sm:flex-row"><div><p class="font-semibold">{{ piece.codigoRastreio }}</p><p class="text-sm text-muted-foreground">{{ piece.descricao }}<span v-if="piece.metal"> · {{ piece.metal }}</span><span v-if="piece.pedras"> · {{ piece.pedras }}</span></p></div><label v-if="can('RECEBER')" class="inline-flex cursor-pointer items-center gap-2 text-sm font-medium text-primary"><Upload class="h-4 w-4" />Adicionar foto<input class="hidden" type="file" accept="image/*" @change="uploadPhoto(piece, $event)" /></label></div><p v-if="piece.estadoConservacao" class="mt-3 text-sm"><span class="font-medium">Estado:</span> {{ piece.estadoConservacao }}</p><div v-if="checklist(piece).length" class="mt-3 flex flex-wrap gap-2"><Badge v-for="item in checklist(piece)" :key="item" variant="outline">{{ item }}</Badge></div><div v-if="piece.fotos?.length" class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><a v-for="photo in piece.fotos" :key="photo.id" :href="photo.url" target="_blank" class="overflow-hidden rounded-lg border bg-muted"><img :src="photo.url" :alt="photo.descricao || `Foto da peça ${piece.codigoRastreio}`" class="aspect-square h-full w-full object-cover" /></a></div></div></CardContent></Card>

      <Card><CardHeader><CardTitle>Orçamento versionado</CardTitle><CardDescription>Serviços, desconto, prazo e materiais planejados antes da baixa.</CardDescription></CardHeader><CardContent class="space-y-5"><div v-if="can('ORCAMENTO') && !budgetLocked" class="space-y-3"><div v-for="(service, index) in budget.servicos" :key="index" class="grid gap-2 sm:grid-cols-[1fr_6rem_9rem_auto]"><Input v-model="service.descricao" placeholder="Serviço" /><Input v-model.number="service.quantidade" type="number" min="1" /><Input v-model.number="service.valor" type="number" min="0" step="0.01" /><Button variant="ghost" size="icon" @click="budget.servicos.splice(index, 1)"><Trash2 class="h-4 w-4" /></Button></div><Button type="button" size="sm" variant="outline" @click="budget.servicos.push({ descricao: '', quantidade: 1, valor: 0 })"><Plus class="mr-2 h-4 w-4" />Serviço</Button><div class="grid gap-3 sm:grid-cols-2"><label class="grid gap-1 text-sm font-medium">Desconto <Input v-model.number="budget.desconto" type="number" min="0" step="0.01" /></label><label class="grid gap-1 text-sm font-medium">Prazo previsto <Input v-model="budget.prazoPrevisto" type="date" /></label></div><div class="space-y-2 rounded-lg border p-3"><p class="text-sm font-semibold">Materiais planejados</p><div v-for="(material, index) in budget.materiais" :key="index" class="grid gap-2 sm:grid-cols-[1fr_10rem_6rem_auto]"><Select2Ajax v-model="material.produtoId" url="/produtos/select2" placeholder="Material" /><select v-model.number="material.pecaId" class="h-10 rounded-md border bg-background px-3 text-sm"><option :value="undefined">Todas as peças</option><option v-for="piece in order.pecas" :key="piece.id" :value="piece.id">{{ piece.codigoRastreio }}</option></select><Input v-model.number="material.quantidade" type="number" min="1" /><Button variant="ghost" size="icon" @click="budget.materiais.splice(index, 1)"><Trash2 class="h-4 w-4" /></Button></div><Button type="button" size="sm" variant="outline" @click="budget.materiais.push({ produtoId: undefined, pecaId: undefined, quantidade: 1 })"><Plus class="mr-2 h-4 w-4" />Material</Button></div><div class="flex flex-wrap items-center gap-3"><Button @click="saveBudget">Salvar nova versão</Button><Button v-if="currentBudget" variant="outline" @click="sendBudget">Gerar link de aprovação</Button><span class="text-sm font-semibold">Total: {{ money(totalBudget) }}</span></div><p v-if="budgetLink" class="break-all rounded-lg bg-muted p-3 text-xs">{{ budgetLink }}</p></div><div v-else-if="currentBudget" class="rounded-lg border p-4"><p class="font-semibold">Versão {{ currentBudget.versao }} · {{ money(currentBudget.valorFinal) }}</p><p class="mt-1 text-sm text-muted-foreground">{{ currentBudget.aprovadoEm ? 'Aprovado' : currentBudget.recusadoEm ? 'Recusado' : currentBudget.enviadoEm ? 'Aguardando cliente' : 'Rascunho' }}</p></div><p v-else class="text-sm text-muted-foreground">Nenhum orçamento criado.</p></CardContent></Card>
      </div>
      <div class="space-y-6"><Card><CardHeader><CardTitle>Materiais e custos</CardTitle><CardDescription>Consumo, devolução e custo histórico por OS.</CardDescription></CardHeader><CardContent class="space-y-3"><div v-for="material in order.materiais" :key="material.id" class="rounded-lg border p-3"><p class="font-medium">{{ material.produto?.nome || `Produto #${material.produtoId}` }}</p><p class="text-xs text-muted-foreground">Planejado: {{ material.quantidadePlanejada }} · Consumido: {{ material.quantidadeConsumida }} · Devolvido: {{ material.quantidadeDevolvida }} · Custo: {{ money(material.custoSnapshot) }}</p><div v-if="can('PRODUCAO') && material.quantidadeConsumida > material.quantidadeDevolvida" class="mt-2 flex gap-2"><Input v-model.number="returnQty[material.id]" type="number" min="1" :max="material.quantidadeConsumida - material.quantidadeDevolvida" /><Button size="sm" variant="outline" @click="returnMaterial(material)">Devolver</Button></div></div><p v-if="!order.materiais?.length" class="text-sm text-muted-foreground">Sem materiais planejados.</p><div class="border-t pt-4"><p class="mb-2 text-sm font-semibold">Custo extra</p><div v-if="can('PRODUCAO') && !closed" class="flex gap-2"><Input v-model="extra.descricao" placeholder="Descrição" /><Input v-model.number="extra.valor" type="number" min="0" step="0.01" class="w-28" /><Button size="sm" @click="addCost">Adicionar</Button></div><p class="mt-2 text-sm">Acumulado: <strong>{{ money(order.custoExtra) }}</strong></p></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Movimentações de estoque</CardTitle></CardHeader><CardContent class="space-y-2"><div v-for="movement in order.movimentacoes || []" :key="movement.id" class="rounded-lg border p-3 text-sm"><p class="font-medium">{{ movement.tipo }} · {{ movement.Produto?.nome || `Produto #${movement.produtoId}` }}</p><p class="text-muted-foreground">{{ movement.quantidade }} un. · {{ new Date(movement.data).toLocaleString('pt-BR') }}</p></div><p v-if="!(order.movimentacoes || []).length" class="text-sm text-muted-foreground">Ainda não houve movimentação.</p></CardContent></Card>
      <Card><CardHeader><CardTitle>Rastreabilidade</CardTitle></CardHeader><CardContent class="space-y-3"><div v-for="event in order.eventos" :key="event.id" class="border-l-2 border-amber-500/60 pl-3"><p class="text-sm">{{ event.descricao }}</p><p class="text-xs text-muted-foreground">{{ new Date(event.createdAt).toLocaleString('pt-BR') }}</p></div></CardContent></Card></div>
    </div>
  </section><div v-else class="p-10 text-center text-sm text-muted-foreground">Carregando ordem…</div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { ArrowLeft, Plus, Trash2, Upload } from 'lucide-vue-next'
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge'; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'; import Select2Ajax from '@/components/formulario/Select2Ajax.vue'
import { OuriveRepository, type OuriveCapability } from '@/repositories/ourive-repository'; import { SiteRepository } from '@/repositories/site-repository'; import { useUiStore } from '@/stores/ui/uiStore'
const route = useRoute(); const router = useRouter(); const toast = useToast(); const ui = useUiStore(); const order = ref<any>(); const budgetLink = ref(''); const returnQty = reactive<Record<number, number>>({}); const extra = reactive({ descricao: '', valor: 0 })
const emptyBudget = () => ({ servicos: [{ descricao: '', quantidade: 1, valor: 0 }], desconto: 0, prazoPrevisto: '', materiais: [] as Array<any> }); const budget = reactive<any>(emptyBudget())
const can = (capability: OuriveCapability) => ui.hasOuriveCapability(capability); const closed = computed(() => ['ENTREGUE', 'RECUSADA', 'CANCELADA'].includes(order.value?.status)); const budgetLocked = computed(() => ['PRODUCAO', 'REVISAO', 'ENTREGUE', 'RECUSADA', 'CANCELADA'].includes(order.value?.status)); const currentBudget = computed(() => order.value?.orcamentos?.[0]); const totalBudget = computed(() => Math.max(0, budget.servicos.reduce((total: number, item: any) => total + Number(item.quantidade || 0) * Number(item.valor || 0), 0) - Number(budget.desconto || 0))); const money = (value: unknown) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0)); const label = (status: string) => ({ RECEBIDA: 'Recebida', ORCAMENTO: 'Orçamento', PRODUCAO: 'Produção', REVISAO: 'Revisão', ENTREGUE: 'Entregue', RECUSADA: 'Recusada', CANCELADA: 'Cancelada' } as Record<string, string>)[status] || status
const checklist = (piece: any) => Array.isArray(piece.checklistRecebimento) ? piece.checklistRecebimento : []
function hydrateBudget() { const current = currentBudget.value; const next = current ? { servicos: current.servicos || [], desconto: Number(current.desconto || 0), prazoPrevisto: current.prazoPrevisto ? String(current.prazoPrevisto).slice(0, 10) : '', materiais: order.value.materiais?.filter((material: any) => !material.quantidadeConsumida).map((material: any) => ({ produtoId: material.produtoId, pecaId: material.pecaId || undefined, quantidade: material.quantidadePlanejada })) || [] } : emptyBudget(); Object.assign(budget, next) }
async function load() { try { order.value = await OuriveRepository.ordem(Number(route.params.id)); hydrateBudget() } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível carregar a ordem.') } }
async function uploadPhoto(piece: any, event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; try { const uploaded = await SiteRepository.uploadSiteImage(file); await OuriveRepository.adicionarFoto(piece.id, { url: uploaded.publicUrl || uploaded.url, descricao: `Foto da peça ${piece.codigoRastreio}` }); await load(); toast.success('Foto adicionada à galeria.') } catch { toast.error('Não foi possível enviar a foto.') } }
async function saveBudget() { if (!budget.servicos.length || budget.servicos.some((item: any) => !item.descricao || Number(item.quantidade) < 1) || budget.materiais.some((item: any) => !item.produtoId || Number(item.quantidade) < 1)) return toast.info('Complete os serviços e materiais planejados.'); try { await OuriveRepository.salvarOrcamento(order.value.id, { ...budget, prazoPrevisto: budget.prazoPrevisto || undefined, desconto: Number(budget.desconto || 0), materiais: budget.materiais.map((item: any) => ({ produtoId: Number(item.produtoId), pecaId: item.pecaId || undefined, quantidade: Number(item.quantidade) })) }); await load(); toast.success('Nova versão do orçamento salva.') } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível salvar o orçamento.') } }
async function sendBudget() { try { const result = await OuriveRepository.enviarOrcamento(order.value.id); budgetLink.value = `${window.location.origin}${result.url}`; await load(); toast.success('Link seguro gerado.') } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível gerar o link.') } }
async function start() { try { await OuriveRepository.iniciarProducao(order.value.id); await load(); toast.success('Produção iniciada e materiais baixados.') } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível iniciar a produção.') } }
async function deliver() { try { await OuriveRepository.entregar(order.value.id); await load(); toast.success('Entrega faturada.') } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível faturar a entrega.') } }
async function returnMaterial(material: any) { const quantity = Number(returnQty[material.id] || 0); if (!quantity) return; try { await OuriveRepository.devolverMaterial(material.id, quantity); await load(); toast.success('Material devolvido ao estoque.') } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível devolver o material.') } }
async function addCost() { if (!extra.descricao || !extra.valor) return; try { await OuriveRepository.adicionarCustoExtra(order.value.id, { descricao: extra.descricao, valor: Number(extra.valor) }); extra.descricao = ''; extra.valor = 0; await load(); toast.success('Custo extra registrado.') } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível registrar o custo.') } }
async function cancel() { const motivo = window.prompt('Informe o motivo do cancelamento:'); if (!motivo) return; try { await OuriveRepository.cancelar(order.value.id, motivo); await load(); toast.success('Ordem cancelada.') } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Devolva integralmente os materiais antes de cancelar.') } }
onMounted(load)
</script>
