<template>
  <section class="space-y-6">
    <div class="rounded-2xl border border-amber-500/20 bg-gradient-to-r from-amber-500/10 to-transparent p-6">
      <p class="text-xs font-semibold tracking-[0.18em] text-amber-700 dark:text-amber-300">ATELIÊ</p>
      <h1 class="mt-1 text-3xl font-bold">Produção</h1>
      <p class="mt-1 text-sm text-muted-foreground">Etapas, responsáveis, revisão e split de comissão.</p>
    </div>
    <div class="grid gap-6 xl:grid-cols-[22rem_1fr]">
      <Card><CardHeader><CardTitle>Ordens em execução</CardTitle></CardHeader><CardContent class="space-y-2"><button v-for="item in orders" :key="item.id" class="w-full rounded-lg border p-3 text-left transition hover:bg-muted" :class="selected?.id === item.id ? 'border-amber-500 bg-amber-500/5' : ''" @click="openOrder(item.id)"><p class="font-semibold">{{ item.codigoRastreio }}</p><p class="text-xs text-muted-foreground">{{ item.ordemServico?.Cliente?.nome }} · {{ item.status }}</p></button><p v-if="!orders.length" class="text-sm text-muted-foreground">Não há ordens disponíveis.</p></CardContent></Card>
      <div v-if="selected" class="space-y-6">
        <Card><CardHeader><div class="flex items-center justify-between"><div><CardTitle>{{ selected.codigoRastreio }}</CardTitle><CardDescription>{{ selected.ordemServico?.descricao }}</CardDescription></div><Button variant="outline" size="sm" @click="router.push({ name: 'ourive-ordem', params: { id: selected.id } })">Abrir OS</Button></div></CardHeader><CardContent class="space-y-3"><div v-for="stage in selected.etapas" :key="stage.id" class="rounded-xl border p-4"><div class="flex flex-col justify-between gap-3 sm:flex-row"><div><p class="font-semibold">{{ stage.nome }}</p><p class="text-xs text-muted-foreground">{{ stage.especialidadeId ? specialtyName(stage.especialidadeId) : 'Sem especialidade' }} · {{ stage.prazoPrevisto ? new Date(stage.prazoPrevisto).toLocaleDateString('pt-BR') : 'Sem prazo' }}</p><p v-if="stage.motivoReprovacao" class="mt-1 text-sm text-destructive">Reprovada: {{ stage.motivoReprovacao }}</p></div><Badge variant="secondary">{{ stage.status.replaceAll('_', ' ') }}</Badge></div><p class="mt-2 text-sm text-muted-foreground">Responsáveis: {{ usersFor(stage.responsavelIds) }}</p><div class="mt-3 flex flex-wrap gap-2"><Button v-if="can('PRODUCAO') && ['PENDENTE', 'REPROVADA'].includes(stage.status)" size="sm" @click="action(stage, 'INICIAR')">Iniciar</Button><Button v-if="can('PRODUCAO') && stage.status === 'EM_EXECUCAO'" size="sm" variant="outline" @click="action(stage, 'ENVIAR_REVISAO')">Enviar à revisão</Button><Button v-if="can('REVISAO') && stage.status === 'AGUARDANDO_REVISAO'" size="sm" @click="action(stage, 'APROVAR')">Aprovar</Button><Button v-if="can('REVISAO') && stage.status === 'AGUARDANDO_REVISAO'" size="sm" variant="destructive" @click="action(stage, 'REPROVAR')">Reprovar</Button></div></div><p v-if="!selected.etapas?.length" class="text-sm text-muted-foreground">Nenhuma etapa criada.</p></CardContent></Card>
        <Card v-if="can('PRODUCAO')"><CardHeader><CardTitle>Nova etapa</CardTitle><CardDescription>Os responsáveis devem ser ourives e ter a especialidade da etapa.</CardDescription></CardHeader><CardContent class="space-y-4"><div class="grid gap-3 md:grid-cols-2"><Input v-model="form.nome" placeholder="Ex.: Ajuste de aro" /><select v-model.number="form.especialidadeId" class="h-10 rounded-md border bg-background px-3"><option :value="undefined">Sem especialidade</option><option v-for="specialty in specialties" :key="specialty.id" :value="specialty.id">{{ specialty.nome }}</option></select><Input v-model="form.prazoPrevisto" type="date" /><Input v-model="form.observacao" placeholder="Observação da etapa" /></div><div><p class="mb-2 text-sm font-medium">Responsáveis</p><div class="flex flex-wrap gap-3"><label v-for="member in ourives" :key="member.id" class="flex items-center gap-2 text-sm"><input v-model="form.responsavelIds" type="checkbox" :value="member.id" />{{ member.nome }}</label></div></div><div class="rounded-lg border p-3"><div class="flex items-center justify-between"><p class="text-sm font-semibold">Split de comissão</p><Button size="sm" variant="outline" @click="addSplit"><Plus class="mr-1 h-4 w-4" />Adicionar</Button></div><div v-for="(split, index) in form.comissoes" :key="index" class="mt-3 grid gap-2 sm:grid-cols-[1fr_10rem_8rem_auto]"><select v-model.number="split.usuarioId" class="h-10 rounded-md border bg-background px-3"><option :value="undefined">Responsável</option><option v-for="member in responsibleMembers" :key="member.id" :value="member.id">{{ member.nome }}</option></select><select v-model="split.tipo" class="h-10 rounded-md border bg-background px-3"><option value="PERCENTUAL">Percentual</option><option value="VALOR_FIXO">Valor fixo</option></select><Input v-model.number="split.referencia" type="number" min="0.01" step="0.01" /><Button size="icon" variant="ghost" @click="form.comissoes.splice(index, 1)"><Trash2 class="h-4 w-4" /></Button></div></div><Button @click="saveStage">Criar etapa</Button></CardContent></Card>
      </div>
      <Card v-else><CardContent class="p-10 text-center text-sm text-muted-foreground">Selecione uma ordem para acompanhar suas etapas.</CardContent></Card>
    </div>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { useToast } from 'vue-toastification'; import { Plus, Trash2 } from 'lucide-vue-next'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge'; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'; import { OuriveRepository, type OuriveCapability } from '@/repositories/ourive-repository'; import { useUiStore } from '@/stores/ui/uiStore'
const router = useRouter(); const toast = useToast(); const ui = useUiStore(); const orders = ref<any[]>([]); const selected = ref<any>(); const team = ref<any[]>([]); const specialties = ref<any[]>([]); const form = reactive<any>({ nome: '', especialidadeId: undefined, prazoPrevisto: '', observacao: '', responsavelIds: [] as number[], comissoes: [] as any[] }); const can = (capability: OuriveCapability) => ui.hasOuriveCapability(capability); const ourives = computed(() => team.value.filter((member) => member.papeis?.includes('OURIVE'))); const responsibleMembers = computed(() => ourives.value.filter((member) => form.responsavelIds.includes(member.id))); const specialtyName = (id: number) => specialties.value.find((item) => item.id === id)?.nome || `Especialidade #${id}`; const usersFor = (ids: number[]) => ids?.map((id) => team.value.find((member) => member.id === id)?.nome || `#${id}`).join(', ') || 'Sem responsável'
async function load() { try { [orders.value, team.value, specialties.value] = await Promise.all([OuriveRepository.ordens().then((data) => data.items.filter((item: any) => !['ENTREGUE', 'RECUSADA', 'CANCELADA'].includes(item.status))), OuriveRepository.equipe(), OuriveRepository.especialidades()]); if (orders.value[0]) await openOrder(orders.value[0].id) } catch { toast.error('Não foi possível carregar a produção.') } }
async function openOrder(id: number) { try { selected.value = await OuriveRepository.ordem(id) } catch { toast.error('Não foi possível abrir a ordem.') } }
function addSplit() { form.comissoes.push({ usuarioId: form.responsavelIds[0], tipo: 'PERCENTUAL', referencia: 0 }) }
async function saveStage() { if (!form.nome || !form.responsavelIds.length || form.comissoes.some((item: any) => !item.usuarioId || !item.referencia)) return toast.info('Informe etapa, responsáveis e os valores de comissão.'); try { await OuriveRepository.criarEtapa(selected.value.id, { ...form, prazoPrevisto: form.prazoPrevisto || undefined, responsavelIds: form.responsavelIds.map(Number), comissoes: form.comissoes.map((item: any) => ({ ...item, usuarioId: Number(item.usuarioId), referencia: Number(item.referencia) })) }); Object.assign(form, { nome: '', especialidadeId: undefined, prazoPrevisto: '', observacao: '', responsavelIds: [], comissoes: [] }); await openOrder(selected.value.id); toast.success('Etapa criada.') } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível criar a etapa.') } }
async function action(stage: any, acao: string) { const motivoReprovacao = acao === 'REPROVAR' ? window.prompt('Motivo da reprovação:') : undefined; if (acao === 'REPROVAR' && !motivoReprovacao) return; try { await OuriveRepository.atualizarEtapa(stage.id, { acao, motivoReprovacao }); await openOrder(selected.value.id); toast.success('Etapa atualizada.') } catch (error: any) { toast.error(error?.response?.data?.error?.message || 'Não foi possível atualizar a etapa.') } }
onMounted(load)
</script>
