import { type Permissoes } from '@/stores/ui/uiStore'
import type { SidebarMenuType } from '@/types/sidebar'
import {
  Bot,
  BrainCircuit,
  Bug,
  CalendarClock,
  ChartPie,
  CircleDollarSign,
  Cog,
  Cpu,
  FileSliders,
  Gauge,
  GitBranchPlus,
  Globe2,
  HandCoins,
  Megaphone,
  KeyRound,
  LifeBuoy,
  Lock,
  ServerCog,
  MessageCircle,
  Sparkles,
  User,
  UserStar,
} from 'lucide-vue-next'

export const sidebarMenuOptionsAdmin = (permissions: Permissoes): SidebarMenuType[] => {
  return [
    {
      nome: 'Dashboard',
      icone: ChartPie,
      color: 'orange',
      link: '/admin',
      key: 'dashboard',
    },
    {
      nome: 'Financeiro',
      icone: CircleDollarSign,
      color: 'emerald',
      show: permissions.financeiro.visualizar,
      key: 'financeiro',
      children: [
        {
          nome: 'Painel',
          link: '/admin/financeiro/painel',
          show: permissions.financeiro.painel,
          icone: ChartPie,
          color: 'emerald',
          key: 'financeiro:painel',
        },
        {
          nome: 'Faturas',
          link: '/admin/faturas',
          icone: CircleDollarSign,
          color: 'emerald',
          key: 'financeiro:faturas',
        },
      ],
    },
    {
      nome: 'Assinantes',
      icone: UserStar,
      show: permissions.clientes.visualizar,
      color: 'violet',
      link: '/admin/assinantes',
      key: 'assinantes',
    },
    {
      nome: 'WhatsApp',
      icone: MessageCircle,
      show: permissions.superadmin,
      color: 'green',
      link: '/admin/whatsapp',
      key: 'whatsapp',
    },
    {
      nome: 'Acessos de suporte',
      icone: LifeBuoy,
      show: permissions.superadmin,
      color: 'yellow',
      link: '/admin/suporte',
      key: 'suporte',
    },
    {
      nome: 'Configurações',
      icone: Cog,
      show: permissions.configuracoes.visualizar,
      color: 'indigo',
      link: '/admin/configuracoes',
      key: 'configuracoes',
    },
    {
      nome: 'Site',
      icone: Globe2,
      show: permissions.superadmin,
      color: 'cyan',
      link: '/admin/site',
      key: 'site',
    },
    {
      nome: 'Inteligência',
      icone: BrainCircuit,
      color: 'violet',
      show: permissions.superadmin,
      key: 'inteligencia',
      children: [
        {
          nome: 'Modelos',
          link: '/admin/inteligencia/modelos',
          icone: Cpu,
          color: 'violet',
          key: 'inteligencia:modelos',
        },
        {
          nome: 'Chaves API',
          link: '/admin/inteligencia/chaves',
          icone: KeyRound,
          color: 'violet',
          key: 'inteligencia:chaves',
        },
        {
          nome: 'Core IA',
          link: '/admin/inteligencia/core',
          icone: Bot,
          color: 'violet',
          key: 'inteligencia:core',
        },
        {
          nome: 'Consumo',
          link: '/admin/inteligencia/consumo',
          icone: Gauge,
          color: 'violet',
          key: 'inteligencia:consumo',
        },
      ],
    },
    {
      nome: 'Monitoramento',
      icone: ServerCog,
      color: 'orange',
      link: '/admin/insights',
      key: 'monitoramento',
    },
    {
      nome: 'Informativos',
      icone: Megaphone,
      color: 'cyan',
      show: permissions.superadmin,
      link: '/admin/informativos',
      key: 'informativos',
    },
    {
      nome: 'Relatos de bug',
      icone: Bug,
      color: 'red',
      show: permissions.superadmin,
      link: '/admin/bugs',
      key: 'bugs',
    },
    {
      nome: 'ERP',
      divisor: true,
      show: permissions.financeiro.visualizar,
    },
    {
      nome: 'Modo ERP',
      color: 'violet',
      icone: FileSliders,
      show: permissions.superadmin,
      link: '/',
      key: 'erp',
    },
  ]
}
