import { type Permissoes } from '@/stores/ui/uiStore'
import type { SidebarMenuType } from '@/types/sidebar'
import {
  Box,
  Boxes,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  ChartPie,
  CircleDollarSign,
  Cog,
  FileBox,
  FileCheck,
  FileCheck2,
  FileDigit,
  GitBranchPlus,
  HandCoins,
  Lock,
  MapPinned,
  Sparkles,
  Tags,
  TicketCheck,
  User,
  UserStar,
  Wrench,
} from 'lucide-vue-next'

export const sidebarMenuArenaOptions = (permissions: Permissoes): SidebarMenuType[] => {
  return [
    {
      nome: 'Painel',
      link: '/arena',
      icone: ChartPie,
      color: 'blue',
    },
    {
      nome: 'Calendário',
      link: '/arena/calendario',
      icone: CalendarCheck2,
      color: 'blue',
    },
    {
      nome: 'Reservas',
      link: '/arena/reservas',
      icone: TicketCheck,
      color: 'blue',
    },
    {
      nome: 'Vendas',
      link: '/arena/comandas',
      icone: Tags,
      color: 'blue',
    },
    {
      nome: 'Quadras',
      link: '/vendas/dashboard',
      icone: MapPinned,
      color: 'blue',
    },
    {
      nome: 'Produtos',
      link: '/produtos',
      icone: Boxes,
      color: 'blue',
    },
    {
      nome: 'Serviços',
      link: '/servicos',
      icone: FileCheck,
      color: 'blue',
    },
    {
      nome: 'Clientes',
      icone: UserStar,
      show: permissions.clientes.visualizar,
      color: 'violet',
      link: '/clientes',
    },
    {
      nome: 'Administração',
      divisor: true,
      show: permissions.admin,
    },
    {
      nome: 'Usuários',
      icone: User,
      show: permissions.admin,
      color: 'purple',
      link: '/administracao/usuarios',
    },
    {
      nome: 'Configurações',
      icone: Cog,
      show: permissions.configuracoes.visualizar,
      color: 'indigo',
      link: '/configuracoes',
    },
    {
      nome: 'Assinatura',
      divisor: true,
      show: permissions.financeiro.visualizar,
    },
    {
      nome: 'Assinatura',
      color: 'orange',
      show: permissions.financeiro.visualizar,
      icone: Sparkles,
      link: '/assinatura/resumo',
    },
    {
      nome: 'Modo Admin',
      color: 'violet',
      icone: Lock,
      show: permissions.superadmin,
      link: '/admin',
    },
    {
      nome: 'Atualizações',
      color: 'blue',
      show: true,
      icone: GitBranchPlus,
      link: '/changelog',
    },
    {
      nome: 'Perfil',
      color: 'blue',
      icone: User,
      link: '/usuario/perfil',
    },
  ]
}
