import { type Permissoes } from '@/stores/ui/uiStore'
import type { SidebarMenuType } from '@/types/sidebar'
import {
  Box,
  Boxes,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  ChartPie,
  CircleDollarSign,
  Cog,
  FileBox,
  FileCheck2,
  GitBranchPlus,
  HandCoins,
  Lock,
  MapPinned,
  ScrollText,
  Sparkles,
  Tags,
  TicketCheck,
  User,
  UserStar,
  Wrench,
} from 'lucide-vue-next'

export const sidebarMenuOptions = (permissions: Permissoes): SidebarMenuType[] => {
  return [
    {
      nome: 'Dashboard',
      icone: ChartPie,
      color: 'orange',
      link: '/',
    },
    {
      nome: 'Arena',
      icone: CalendarCheck,
      show: false,
      color: 'blue',
      children: [
        {
          nome: 'Painel',
          link: '/vendas/dashboard',
          icone: ChartPie,
          color: 'blue',
        },
        {
          nome: 'Calendário',
          link: '/vendas',
          icone: CalendarCheck2,
          color: 'blue',
        },
        {
          nome: 'Reservas',
          link: '/vendas/dashboard',
          icone: TicketCheck,
          color: 'blue',
        },
        {
          nome: 'Quadras',
          link: '/vendas/dashboard',
          icone: MapPinned,
          color: 'blue',
        },
      ],
    },
    {
      nome: 'Vendas',
      icone: Tags,
      color: 'green',
      show: permissions.vendas.visualizar,
      children: [
        {
          nome: 'Painel',
          link: '/vendas/dashboard',
          show: permissions.vendas.painel,
          icone: ChartPie,
          color: 'green',
        },
        {
          nome: 'Vendas',
          link: '/vendas',
          icone: Tags,
          color: 'green',
        },
      ],
    },
    {
      nome: 'Financeiro',
      icone: CircleDollarSign,
      color: 'emerald',
      show: permissions.financeiro.visualizar,
      children: [
        {
          nome: 'Painel',
          link: '/financeiro/painel',
          show: permissions.financeiro.painel,
          icone: ChartPie,
          color: 'emerald',
        },
        {
          nome: 'Lançamentos',
          link: '/financeiro/lancamentos',
          icone: CircleDollarSign,
          color: 'emerald',
        },
        {
          nome: 'Acompanhamento',
          link: '/financeiro/acompanhamento',
          icone: CalendarClock,
          color: 'emerald',
        },
        {
          nome: 'Cobranças',
          link: '/financeiro/cobrancas',
          icone: HandCoins,
          color: 'emerald',
        },
      ],
    },
    {
      nome: 'Produtos',
      icone: Box,
      color: 'blue',
      show: permissions.produtos.visualizar,
      children: [
        {
          nome: 'Painel',
          link: '/produtos/dashboard',
          show: permissions.produtos.painel,
          icone: ChartPie,
          color: 'blue',
        },
        {
          nome: 'Produtos',
          link: '/produtos',
          icone: Boxes,
          color: 'blue',
        },
      ],
    },
    {
      nome: 'Desenvolvimento',
      divisor: true,
      show: false,
    },
    {
      nome: 'Serviços',
      icone: FileBox,
      show: permissions.servicos.visualizar && permissions.superadmin,
      color: 'yellow',
      children: [
        { nome: 'Painel', link: '/servicos/painel', color: 'yellow', icone: ChartPie },
        { nome: 'Ordens de serviço', link: '/servicos/ordens', color: 'yellow', icone: ScrollText },
        { nome: 'Serviços', link: '/servicos', color: 'yellow', icone: Wrench },
      ],
    },
    {
      nome: 'Notas Fiscais',
      icone: FileCheck2,
      show: false,
      color: 'cyan',
      link: '/notas-fiscais',
      children: [
        // { nome: "Painel", link: "/financeiro/painel", icone: "fa-solid fa-chart-pie" },
        // { nome: "Lançamentos", link: "/financeiro/lancamentos", icone: "fa-solid fa-coins" },
      ],
    },
    {
      nome: 'Clientes',
      icone: UserStar,
      show: permissions.clientes.visualizar,
      color: 'violet',
      link: '/clientes',
    },
    {
      nome: 'Administração',
      divisor: true,
      show: permissions.admin,
    },
    {
      nome: 'Usuários',
      icone: User,
      show: permissions.admin,
      color: 'purple',
      link: '/administracao/usuarios',
    },
    {
      nome: 'Configurações',
      icone: Cog,
      show: permissions.configuracoes.visualizar,
      color: 'indigo',
      link: '/configuracoes',
    },
    {
      nome: 'Assinatura',
      divisor: true,
      show: permissions.financeiro.visualizar,
    },
    {
      nome: 'Assinatura',
      color: 'orange',
      show: permissions.financeiro.visualizar,
      icone: Sparkles,
      link: '/assinatura/resumo',
    },
    {
      nome: 'Modo Admin',
      color: 'violet',
      icone: Lock,
      show: permissions.superadmin,
      link: '/admin',
    },
    {
      nome: 'Atualizações',
      color: 'blue',
      show: true,
      icone: GitBranchPlus,
      link: '/changelog',
    },
    {
      nome: 'Perfil',
      color: 'blue',
      icone: User,
      link: '/usuario/perfil',
    },
  ]
}
